



import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.geom.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.util.Random;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * welcome_screen.java
 *
 * Created on Jan 31, 2012, 8:01:26 PM
 */
/**
 *
 * @author deweshiitkgp
 */

public class welcome_screen extends javax.swing.JApplet { 
    FileWriter snake,ladder;
    BufferedWriter br1,br2;
 second s;
int players_no=2,board_size=8;
    /** Creates new form welcome public welcome_screen() {_screen */
   
       
         
       


    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jButton3 = new javax.swing.JButton();
        welcome_screen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setting = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        play = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();

        jButton3.setText("jButton3");

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //setTitle("welcome");

        welcome_screen.setToolTipText("");
        welcome_screen.setName("welcome"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel1.setText("Number of players:");

        jComboBox1.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout welcome_screenLayout = new javax.swing.GroupLayout(welcome_screen);
        welcome_screen.setLayout(welcome_screenLayout);
        welcome_screenLayout.setHorizontalGroup(
            welcome_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_screenLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(welcome_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(welcome_screenLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(welcome_screenLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        welcome_screenLayout.setVerticalGroup(
            welcome_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcome_screenLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(welcome_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(welcome_screenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jButton4.setBackground(new java.awt.Color(204, 255, 0));
        jButton4.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/done_blue.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setText("set default");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DEFAULT", "5 X 5", "6 X 6", "7 X 7", "8 X 8", "9 X 9 ", "10X10", "11X11", "12X12" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel3.setText("RESIZE BOARD :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("board size", jPanel1);

        jLabel4.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel4.setText("head");

        jLabel5.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel5.setText("tail");

        jButton7.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_b.png"))); // NOI18N
        jButton7.setToolTipText("add");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextField1.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("15,5\n22,19\n35,25\n24,4\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("snake position", jPanel2);

        jLabel6.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel6.setText("end");

        jButton8.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_b.png"))); // NOI18N
        jButton8.setToolTipText("add");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField3.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel7.setText("start");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("2,14\n12,26\n40,46\n52,62\n77,80");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("ladder position", jPanel3);

        javax.swing.GroupLayout settingLayout = new javax.swing.GroupLayout(setting);
        setting.setLayout(settingLayout);
        settingLayout.setHorizontalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingLayout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        settingLayout.setVerticalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jButton5.setBackground(null);
        jButton5.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 0, 51));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start.png"))); // NOI18N
        jButton9.setToolTipText("start");
        jButton9.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), null));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Curlz MT", 1, 18)); // NOI18N
        jLabel8.setText("PLAYER 1:");

        jLabel9.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel9.setText("PLAYER 3:");

        jLabel10.setFont(new java.awt.Font("Curlz MT", 1, 18));
        jLabel10.setText("PLAYER 2:");

        jTextField5.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setMinimumSize(new java.awt.Dimension(50, 20));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RED" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GREEN" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BLUE" }));
        jComboBox5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout playLayout = new javax.swing.GroupLayout(play);
        play.setLayout(playLayout);
        playLayout.setHorizontalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox4, 0, 97, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 97, Short.MAX_VALUE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, 97, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        playLayout.setVerticalGroup(
            playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcome_screen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(welcome_screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //pack();
    }// </editor-fold>                        
int temp=0;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
players_no=jComboBox1.getSelectedIndex()+2;
        temp=1;
welcome_screen.setVisible(false);    
play.setVisible(true);
setting.setVisible(false);
if(jComboBox1.getSelectedIndex()==0){
 jLabel9.setVisible(false);
 jTextField6.setVisible(false);
 jComboBox5.setVisible(false);
}
if(jComboBox1.getSelectedIndex()==1){
 jLabel9.setVisible(true);
 jTextField6.setVisible(true);
jComboBox5.setVisible(true); 
}
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
players_no=jComboBox1.getSelectedIndex()+2;
        welcome_screen.setVisible(false);        // TODO add your handling code here:
setting.setVisible(true);
play.setVisible(false);

    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      welcome_screen.setVisible(true);        // TODO add your handling code here:
setting.setVisible(false); 
play.setVisible(false);
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(temp==1 || temp==3)
{
    welcome_screen.setVisible(true);  
setting.setVisible(false);
    }
else if(temp==2)
{
    setting.setVisible(true);
welcome_screen.setVisible(false);  
}

play.setVisible(false);

    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        try {
            snake=new FileWriter("E:\\snake.txt");
            ladder=new FileWriter("E:\\ladder.txt");
            br1=new BufferedWriter(snake);
            br2=new BufferedWriter(ladder);
            br1.write(jTextArea1.getText());
            br2.write(jTextArea2.getText());
            br1.close();
            br2.close();
            snake.close();
            ladder.close();
        } catch (IOException ex) {
            Logger.getLogger(welcome_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(jComboBox2.getSelectedIndex()==0)
    board_size=8;
else
        board_size=jComboBox2.getSelectedIndex()+4;
        JOptionPane.showMessageDialog(this, "board updated");
        setting.setVisible(false);
        welcome_screen.setVisible(true);
        play.setVisible(false);
      /*  temp=2;     
      setting.setVisible(false);
       play.setVisible(true);
         welcome_screen.setVisible(false);
         if(jComboBox1.getSelectedIndex()==0){
 jLabel9.setVisible(false);
 jTextField6.setVisible(false);
}
if(jComboBox1.getSelectedIndex()==1){
 jLabel9.setVisible(true);
 jTextField6.setVisible(true);
}*/
    }                                        

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {                                   
jLabel2.setForeground(Color.yellow);        // TODO add your handling code here:
    }                                  

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {                                    
    jLabel2.setForeground(Color.black);     // TODO add your handling code here:
    }                                   

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(Integer.valueOf(jTextField1.getText())>Integer.valueOf(jTextField2.getText()))
{
        jTextArea1.append(jTextField1.getText()+","+jTextField2.getText()+"\n");
jTextField1.setText("");
        jTextField2.setText("");
}
else
    JOptionPane.showMessageDialog(this, "head should be greater than tail");
    
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
if(Integer.valueOf(jTextField3.getText())<Integer.valueOf(jTextField4.getText()))
{
    jTextArea2.append(jTextField3.getText()+","+jTextField4.getText()+"\n");
    jTextField3.setText("");
        jTextField4.setText("");
}   else
    JOptionPane.showMessageDialog(this, "start should be less than end");

    }                                        

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
    /* setting.setVisible(false);
       play.setVisible(true);
         welcome_screen.setVisible(false);
         temp=3;
         if(jComboBox1.getSelectedIndex()==0){
 jLabel9.setVisible(false);
 jTextField6.setVisible(false);
}
if(jComboBox1.getSelectedIndex()==1){
 jLabel9.setVisible(true);
 jTextField6.setVisible(true);
}*/// TODO add your handling code here:*/
       jTextArea2.setText("2,14"+"\n"+"13,24"+"\n"+"40,55"+"\n"+"52,79"+"\n"+"77,92");
       jTextArea1.setText("15,5"+"\n"+"35,25"+"\n"+"45,4"+"\n"+"23,19");
       jComboBox2.setSelectedItem(0);
    }                                    

  
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         

       
      FileWriter fstream;
        try {
            fstream = new FileWriter("E:\\database1.txt");
        
  BufferedWriter out = new BufferedWriter(fstream);
      
            out.write(String.valueOf(players_no)+"\n"+String.valueOf(board_size));
            out.close();
            fstream.close();
        } catch (IOException ex) {
            Logger.getLogger(welcome_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            s = new second();
        } catch (IOException ex) {
            Logger.getLogger(welcome_screen.class.getName()).log(Level.SEVERE, null, ex);
        }
JFrame frm = new JFrame();       
            frm.setVisible(true);
            frm.setSize(board_size*50,(board_size+4)*50+30);
            frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frm.add(s);
            frm.setResizable(false);
            //this.setVisible(false);
              jTextField5.setEditable(false);
            jTextField6.setEditable(false);
            jTextField7.setEditable(false);
            jButton9.setVisible(false);
            jButton5.setVisible(false);frm.setLocation(450,3);
    }                                        

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
ImageIcon img;
    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {                                    
 
jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b_1.png")));  
    }                                   

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png")));
              // TODO add your handling code here:
    }                                    

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {                                      
 
jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/b_1.png")));// TODO add your handling code here):
    }                                     

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); 
    }                                    

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {                                      
 jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settingr.png"))); // TODO add your handling code here:        // TODO add your handling code here:
    }                                     

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting.png")));        // TODO add your handling code here:
    }                                    

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {                                      
jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startg.png")));        // TODO add your handling code here:
    }                                     

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {                                     
     jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start.png")));     // TODO add your handling code here:
    }                                    

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {                                      
jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/startg.png")));          // TODO add your handling code here:
    }                                     

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start.png")));          // TODO add your handling code here:
    }                                    

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {                                      
jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/done_red.png")));        // TODO add your handling code here:
    }                                     

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/done_blue.png")));          // TODO add your handling code here:
    }                                    

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {                                      
jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_r.png")));          // TODO add your handling code here:
    }                                     

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_b.png")));          // TODO add your handling code here:
    }                                    

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {                                      
jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_r.png")));          // TODO add your handling code here:
    }                                     

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {                                     
jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_b.png")));          // TODO add your handling code here:
    }                                    

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

     
    /**
     * @param args the command line arguments
     */
  public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                 initComponents();
            setSize(430,330);
                new welcome_screen().setVisible(true);
            }
            
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel play;
    private javax.swing.JPanel setting;
    private javax.swing.JPanel welcome_screen;
    // End of variables declaration                   

}
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */




class second extends JPanel implements ActionListener{
    Timer t = new Timer(5,this);
    JPanel con=new JPanel();
  FileInputStream snk=new FileInputStream("E:\\snake.txt");
            DataInputStream dsnk=new DataInputStream(snk);
            BufferedReader bsnk=new BufferedReader(new InputStreamReader(dsnk));
             FileInputStream snk1=new FileInputStream("E:\\ladder.txt");
            DataInputStream dsnk1=new DataInputStream(snk1);
            BufferedReader bsnk1=new BufferedReader(new InputStreamReader(dsnk1));
             FileInputStream tsnk=new FileInputStream("E:\\snake.txt");
            DataInputStream tdsnk=new DataInputStream(tsnk);
            BufferedReader tbsnk=new BufferedReader(new InputStreamReader(tdsnk));
             FileInputStream tsnk1=new FileInputStream("E:\\ladder.txt");
            DataInputStream tdsnk1=new DataInputStream(tsnk1);
            BufferedReader tbsnk1=new BufferedReader(new InputStreamReader(tdsnk1));
           
  JLabel pic =new JLabel();
  JButton click ;
  JTextArea test;
  int b_size,p_no;
  // time se;
  int i[]={0,0,0},destination[]={0,0,0},temp0,snakehead[]={15,23,35,45},snaketail[]={5,19,25,4},snake_no=0,ladder_no=0,ladders[]={2,13,40,52,77},laddere[]={14,24,55,79,92};
  int coll,in,q=0,p[]={0,0,0};
  String snake[][],ladder[][];
  boolean snaked=false;
  private ImageIcon image1,image2;
   Random d;
    int lev=1,sec=0,z=1,x[]={0,100,50},y[]={100,100,100},temp,temp1;
    
    public second() throws IOException{
        
        
        t.start();
 while(tbsnk.readLine() != null ){
              snake_no++;  
            }
  while(tbsnk1.readLine() != null ){
              ladder_no++;  
            }
 snake=new String[snake_no][2];
 ladder=new String[ladder_no][2];

 String as,ass;
 int i1=0,j1=0;
 for(i1=0;i1<snake_no;i1++){
     as=bsnk.readLine();
     snake[i1]=as.split(",");
 }
 for(j1=0;j1<ladder_no;j1++){
     ass=bsnk1.readLine();
     //System.out.println(ass);
     ladder[j1]=ass.split(",");
     System.out.println(ladder[j1][1]);
     
 }
 bsnk.close();
bsnk1.close();
dsnk.close();
dsnk1.close();
snk.close();
snk1.close();
tbsnk.close();
tbsnk1.close();
tdsnk.close();
tdsnk1.close();
tsnk.close();
tsnk1.close();

 
        setFocusable(true);
        setFocusTraversalKeysEnabled(false);
                click=new JButton("");
                
               // se=new time();
                click.setSize(100, 100);
                //this.setLayout(new GridLayout(0,2));
                click.setBorderPainted(false);
      click.setContentAreaFilled(false);
                click.addActionListener(this);
                click.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                 click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clickMouseExited(evt);
            }

            private void clickMouseEntered(MouseEvent evt) {
                click.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice.png")));
            }

            private void clickMouseExited(MouseEvent evt) {
                click.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice_off.png")));
            }
        });
                click.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice_off.png")));
                JPanel con1=new JPanel();
                con1.setOpaque(false);
                
                add(con1);
                add(click);
                
                click.setLocation(400,0);
        try {
            FileInputStream fstr=new FileInputStream("E:\\database1.txt");
            DataInputStream dis=new DataInputStream(fstr);
            BufferedReader br=new BufferedReader(new InputStreamReader(dis));
            
            p_no=Integer.valueOf(br.readLine());
            b_size=Integer.valueOf(br.readLine());
            //System.out.println(p_no+"\n"+b_size);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(second.class.getName()).log(Level.SEVERE, null, ex);
        }
               
                
    }
    int xco=0,yco=0;
    JButton click1=new JButton("");
    @Override
    public void paintComponent(Graphics g){
      super.paintComponent(g); 
      super.setBackground(Color.pink);
      this.add(con);
      con.setSize(500,150);
      con.setBackground(Color.yellow);
      con.setVisible(true);
      click1.setSize(600,150);
      click1.setBorderPainted(false);
      click1.setContentAreaFilled(false);
      
             click1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake_banne1r.jpg")));
              
con.setOpaque(false);
con.add(click1);

            Graphics2D g2 = (Graphics2D) g;
            g2.setFont(new Font("Serif",Font.PLAIN, 30));
     // Rectangle2D rec = new Rectangle2D.Double(0,0,50,50);
      Ellipse2D circle=new Ellipse2D.Double(x[0],y[0],50,50);
      Ellipse2D circle1=new Ellipse2D.Double(x[1],y[1],50,50);
      Ellipse2D circle2=null;
      if(p_no==3)
         circle2=new Ellipse2D.Double(x[2],y[2],50,50);
     // g2.setColor(Color.white);
     //g2.fill(rec);
      int num=1,yc=1;
     
         for(yco=b_size+2;yco>=3;yco--,yc++)
         {
             for(xco=0;xco<b_size;xco++,num++){
                 if((xco+yco-3)%2==0){
              g2.setColor(Color.black);
              
             g2.fillRect(xco*50, yco*50, 50, 50);
             g2.setColor(Color.white);
             if(yc%2==0){
                 for(temp=0;temp<snake_no;temp++){
                     if((yc*b_size-xco)==Integer.valueOf(snake[temp][0]))
                         g2.setColor(Color.red);
                 }
                 for(temp=0;temp<ladder_no;temp++){
                     if((yc*b_size-xco)==Integer.valueOf(ladder[temp][0]))
                         g2.setColor(Color.green);
                 }
                 g2.drawString(String.valueOf(yc*b_size-xco),xco*50,yco*50+50);
                 g2.setColor(Color.white);
             }
             else{
                  for(temp=0;temp<snake_no;temp++){
                     if((num)==Integer.valueOf(snake[temp][0]))
                         g2.setColor(Color.red);
                 }
                 for(temp=0;temp<ladder_no;temp++){
                     if((num)==Integer.valueOf(ladder[temp][0]))
                         g2.setColor(Color.green);
                 }
                 
                 g2.drawString(String.valueOf(num),xco*50,yco*50+50);
             g2.setColor(Color.white);
             }
                 }
         else{         
     g2.setColor(Color.white);
     g2.fillRect(xco*50, yco*50, 50, 50);
     g2.setColor(Color.black);
      if(yc%2==0){ for(temp=0;temp<snake_no;temp++){
                     if((yc*b_size-xco)==Integer.valueOf(snake[temp][0]))
                         g2.setColor(Color.red);
                 }
                 for(temp=0;temp<ladder_no;temp++){
                     if((yc*b_size-xco)==Integer.valueOf(ladder[temp][0]))
                         g2.setColor(Color.green);
                 }
                 g2.drawString(String.valueOf(yc*b_size-xco),xco*50,yco*50+50);
                   g2.setColor(Color.black);
      }
      else{
          for(temp=0;temp<snake_no;temp++){
                     if((num)==Integer.valueOf(snake[temp][0]))
                         g2.setColor(Color.red);
                 }
                 for(temp=0;temp<ladder_no;temp++){
                     if((num)==Integer.valueOf(ladder[temp][0]))
                         g2.setColor(Color.green);
                 }
      
    g2.drawString(String.valueOf(num),xco*50,yco*50+50);
      g2.setColor(Color.black);
         }
                 }
    } 
    }
         int s[][],s1[][],l1[][],l[][];
      s=new int[snake_no][2];
      l=new int[ladder_no][2];
      s1=new int[snake_no][2];
      l1=new int[ladder_no][2];
       g2.setStroke(new java.awt.BasicStroke(7));
      ///////////////////////////////////////////////////////////////////////////////////////////////////////////
      g2.setColor(Color.red);
      
      for(temp=0;temp < snake_no;temp++){
          
         temp0=Integer.valueOf(snake[temp][0])%b_size;
        coll=(int) Integer.valueOf(snake[temp][0])/b_size;
        if(temp0==0){
        	--coll;
           temp0=b_size-1;}
        else if(Integer.valueOf(snake[temp][0])>0)
            --temp0;
        
        s[temp][0]=(2+b_size)*50-(coll*50);
        if(coll%2==0){
            s[temp][1]=temp0*50;
        }
        else{
            s[temp][1]=(b_size-1)*50-temp0*50;
        }
        
            temp0=Integer.valueOf(snake[temp][1])%b_size;
        coll=(int) Integer.valueOf(snake[temp][1])/b_size;
        if(temp0==0){
        	--coll;
           temp0=b_size-1;}
        else if(Integer.valueOf(snake[temp][1])>0)
            --temp0;
        
        s1[temp][0]=(2+b_size)*50-(coll*50);
        if(coll%2==0){
            s1[temp][1]=temp0*50;
        }
        else{
            s1[temp][1]=(b_size-1)*50-temp0*50;
        }
      Composite originalComposite = g2.getComposite();
      g2.setComposite(makeComposite((float) 0.6));
    g2.setPaint(Color.red);
    g2.fillRect(s[temp][1],s[temp][0],50,50);
    
        g2.drawLine(s[temp][1]+20, s[temp][0]+20, s1[temp][1]+20, s1[temp][0]+20);
        g2.setComposite(originalComposite);
      }
          ///////////////////////////////////////////////////////////////////////////////////////////////////////////
      g2.setColor(Color.green);
      
      for(temp=0;temp < ladder_no;temp++){
          
         temp0=Integer.valueOf(ladder[temp][0])%b_size;
        coll=(int) Integer.valueOf(ladder[temp][0])/b_size;
        if(temp0==0){
        	--coll;
           temp0=b_size-1;}
        else if(Integer.valueOf(ladder[temp][0])>0)
            --temp0;
        
        l[temp][0]=(2+b_size)*50-(coll*50);
        if(coll%2==0){
            l[temp][1]=temp0*50;
        }
        else{
            l[temp][1]=(b_size-1)*50-temp0*50;
        }
        
            temp0=Integer.valueOf(ladder[temp][1])%b_size;
        coll=(int) Integer.valueOf(ladder[temp][1])/b_size;
        if(temp0==0){
        	--coll;
           temp0=b_size-1;}
        else if(Integer.valueOf(ladder[temp][1])>0)
            --temp0;
        
        l1[temp][0]=(2+b_size)*50-(coll*50);
        if(coll%2==0){
            l1[temp][1]=temp0*50;
        }
        else{
            l1[temp][1]=(b_size-1)*50-temp0*50;
        }
      float op=(float) 0.6;
        Composite originalComposite = g2.getComposite();
      g2.setComposite(makeComposite(op));
    g2.setPaint(Color.blue);
    g2.fillRect(l[temp][1],l[temp][0],50,50);
    
        g2.drawLine(l[temp][1]+20, l[temp][0]+20, l1[temp][1]+20, l1[temp][0]+20);
        g2.setComposite(originalComposite);
      }
          
     g2.setColor(Color.RED);
     g2.fill(circle);
     g2.setColor(Color.GREEN);
     g2.fill(circle1);
      if(p_no==3){
     g2.setColor(Color.blue);
     g2.fill(circle2);
      }
      g2.setFont(new Font("Serif",Font.BOLD, 38));
      g2.setColor(Color.red);
      g2.drawString(tex, 0, (b_size+4)*50-12);
     
    }
String tex="green roll the dice";
  private AlphaComposite makeComposite(float alpha) {
    int type = AlphaComposite.SRC_OVER;
    return(AlphaComposite.getInstance(type, alpha));
  }
    public void actionPerformed(ActionEvent e) {
        
        if(e.getSource()==click){
             d=new Random();
in=d.nextInt(6)+1;
            JOptionPane.showMessageDialog(this,"the number is"+in);
            if(p_no==2){
                if(q==0){
            	q=1;
                p[0]+=1;}
                else{
            	q=0;p[1]++;}
            }
            else
            {
               /* if(q==0){
            	q=1;p[0]++;}
                else if(q==2){
            	q=0;p[1]++;}
                else{
                    q=2;
                p[2]++;}*/
                if(p[0]==p[1] && p[1]==p[2]){
                    q=1;p[0]++;
                }
                else if(p[0]>p[1]){
                    q=0;p[1]++;
                }
                else if(p[1]>p[2]){
                    q=2;p[2]++;
                }
            }
           destination[q]=i[q]+in;
           i[q]=destination[q];
           if(i[q]>(b_size*b_size))
           {
        	   JOptionPane.showMessageDialog(this,"sorry...boundry");
        	   i[q]-=in;
           }
           int ls=i[q];
          for(temp=0;temp<snake_no;temp++){
        	  if(i[q]==Integer.valueOf(snake[temp][0])){
        		  
                          //System.out.println(snake[temp][1]);
        		  i[q]=Integer.valueOf(snake[temp][1]);
                          repaint();
                          JOptionPane.showMessageDialog(this,"snake at " + ls + " got u");
        	  }
          }
          
          for(temp=0;temp<ladder_no;temp++){
        	  if(i[q]==Integer.valueOf(ladder[temp][0])){
                           //System.out.println(Integer.valueOf(ladder[temp][1]));
        		  i[q]=Integer.valueOf(ladder[temp][1]);
                          repaint();
                          JOptionPane.showMessageDialog(this,"ladder at "+ls);
        	  }
          }
           
        temp0=i[q]%b_size;
        coll=(int) i[q]/b_size;
        if(temp0==0){
        	--coll;
           temp0=b_size-1;}
        else if(i[q]>0)
            --temp0;
        
        y[q]=(2+b_size)*50-(coll*50);
        if(coll%2==0){
            x[q]=temp0*50;
        }
        else{
            x[q]=(b_size-1)*50-temp0*50;
        }
        if(p_no==2){
                if(q==0){
            	tex="green roll the dice";
                }
                else{
            	tex="red roll the dice";
            }
        }
            else
            {
         if(p[0]==p[1] && p[1]==p[2]){
                    tex="green roll the dice";
                }
                else if(p[0]>p[1]){
                    tex="red roll the dice";
                }
                else if(p[1]>p[2]){
                    tex="blue roll the dice";
                }
            }
         
        /*if(q==0){
        	//click.setText("blue::");
            tex="blue roll the dice ";
        }
        else if(q==1)
        {//click.setText("red::");
            tex="red roll the dice";
        }
        else
        {
        	//click.setText("green::");
            tex="green roll the dice";
        }*/
         repaint();
        if(i[q]==(b_size*b_size))
        {
     	   JOptionPane.showMessageDialog(null,"player "+(q+1)+ " is the winner"+"\n"+"SCORE:"+(p[q]+1)); 
                try {FileWriter winner = null;BufferedWriter win = null;
                
               
                    FileInputStream w=new FileInputStream("E:\\winner"+b_size+".txt");
                    DataInputStream di=new DataInputStream(w);
                    BufferedReader w1=new BufferedReader(new InputStreamReader(di));
                    
                    if(p[q]+1<Integer.valueOf(w1.read()))
                    {w.close();
                    di.close();
                    w1.close();
                     winner =new FileWriter("E:\\winner"+b_size+".txt");
                    win=new BufferedWriter(winner);
                        JOptionPane.showMessageDialog(null,"congozzz u have a new high score"); 
                        
                    win.write(String.valueOf(p[q]+1));
                    }
                    else{
                        w.close();
                    di.close();
                    w1.close();
                    }
                    win.close();
                    winner.close();
                } catch (IOException ex) {
                    Logger.getLogger(second.class.getName()).log(Level.SEVERE, null, ex);
                }
     	   System.exit(1);
        }
        	
        }
       
        
       /*if((x1-x) < 30 && (x1-x) > -30 && (y1-y) < 30 && (y1-y) > -30){
            temp=velx;
            temp1=vely;
            velx=-velx1;vely=vely1;velx1=temp;vely1=temp1;
            JOptionPane.showMessageDialog(null,"CONGRATULATION\ngreen u won");
            x=0;y=500;x1=500;y1=500;
             JOptionPane.showMessageDialog(null,"green-cop\nred-theaf");
             x=0;y=500;velx=0;vely=0;x1=500;y1=500;velx1=0;vely1=0;z=1.5;lev=0;
        }*/
       /* if(destination>i){
         
        runf();
        
    }
        if(destination==i && snaked==true){
            destination=snaketail[snake_no]-1;
            snaked=false;
        }
        
        if(destination<i)
        {
            funr();
           
        }*/
    }
   
 
     
      /*  public void runf(){
             if(x<0 ||x>500){
            velx=-velx;
            y-=50;
            test.append(x+"::"+y+"()");
            coll++;
        }
      if(y<0 ||y>500){
            vely=0;velx=0;
            
        }
        if(x1<0 ||x1>500){
            velx1=-velx1;
            y1-=50;
        }
      if(y1<0 ||y1>500){
            vely1=0;
            velx1=0;
        }
      repaint();
        x+=velx;
       y+=vely;
       
        x1+=velx1;
       y1+=vely1;
        }

    private void funr() {
       
        if(x<0 ||x>500){
            velx=-velx;
            y+=50;
            //test.append(x+"::"+y+"()");
            coll--;
        }
      if(y<0 ||y>500){
            vely=0;velx=0;
            
        }
        if(x1<0 ||x1>500){
            velx1=-velx1;
            y1+=50;
        }
      if(y1<0 ||y1>500){
            vely1=0;
            velx1=0;
        }
      repaint();
        x-=velx;
       y-=vely;
       
        x1-=velx1;
       y1-=vely1;
    }*/
}